export const SET_LIST_TICKET = 'SET_TICKET_LIST';
export const ADD_TICKET = 'ADD_TICKET';
export const ADD_LIST_TICKET_PAGE = 'ADD_LIST_TICKET_PAGE';
export const DELETE_PRODUCT = 'DELETE_LIST_PRODUCT';
