export default [
  {
    name: 'Free Plan',
    price: 0.0,
    listContent: [
      '1 Product',
      'Store Warranty Information',
      'Optional Warranty Registration',
      'Warranty Retrival Anytime',
      'File Warranty Claim',
      'Delete Warranty',
      'Update Warranty Any Time',
      'Highly Secured Cloud',
      'Auto Renewal',
      'Cancel Any Time',
    ],
  },
  {
    name: 'Home Plan',
    price: 1.99,
    listContent: [
      '10 Products',
      'Store Warranty Information',
      'Optional Warranty Registration',
      'Warranty Retrival Anytime',
      'File Warranty Claim',
      'Delete Warranty',
      'Update Warranty Any Time',
      'Highly Secured Cloud',
      'Auto Renewal',
      'Cancel Any Time',
    ],
  },
  {
    name: 'Business Plan',
    price: 3.99,
    listContent: [
      '100 Products',
      'Store Warranty Information',
      'Optional Warranty Registration',
      'Warranty Retrival Anytime',
      'File Warranty Claim',
      'Delete Warranty',
      'Update Warranty Any Time',
      'Highly Secured Cloud',
      'Auto Renewal',
      'Cancel Any Time',
    ],
  },
];
